name: Script

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Script
        uses: actions/github-script@v6
        with:
          script: |
            const comment = 'Gracias por tu Pull Request';
            const issue_number = context.payload.pull_request.number;
            await github.issues.createComment({
              ...context.repo,
              issue_number,
              body: comment
            });
