name: Script

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Write .env
        run: echo "${{ secrets.DOT_ENV }}" >> .env
      - name: Read .env
        run: cat .env
      - name: Build
        run: npm run build

  dev-comment:
    runs-on: ubuntu-22.04
    environment: dev
    env:
      VARIABLE_LOCAL: "Hola Mundo DEV"
      VARIABLE_ENTORNO: ${{ vars.MI_PRIMER_VARIABLE }}
    steps:
      - name: Ver variable
        run: |
          echo "VALOR DE LA VARIABLE: ${{ vars.MI_PRIMER_VARIABLE }}"
          echo "VALOR DE LA VARIABLE_LOCAL: ${{ env.VARIABLE_LOCAL }}"
          echo "VALOR DE LA VARIABLE_ENTORNO: ${{ env.VARIABLE_ENTORNO }}"
          echo "VALOR DE LA SECRET: ${{ secrets.MI_PRIMER_SECRET }}"

  stg-comment:
    runs-on: ubuntu-22.04
    environment: stg
    env:
      VARIABLE_LOCAL: "Hola Mundo STG"
      VARIABLE_ENTORNO: ${{ vars.MI_PRIMER_VARIABLE }}
    steps:
      - name: Ver variable
        run: |
          echo "VALOR DE LA VARIABLE: ${{ vars.MI_PRIMER_VARIABLE }}"
          echo "VALOR DE LA VARIABLE_LOCAL: ${{ env.VARIABLE_LOCAL }}"
          echo "VALOR DE LA VARIABLE_ENTORNO: ${{ env.VARIABLE_ENTORNO }}"
          echo "VALOR DE LA SECRET: ${{ secrets.MI_PRIMER_SECRET }}"
