name: Script

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Script
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Gracias por tu Pull Request'
            })