name: Script

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  dev-comment:
    runs-on: ubuntu-22.04
    environment: dev
    env:
      VARIABLE_LOCAL: "Hola Mundo"
      VARIABLE_ENTORNO: ${{ vars.MI_PRIMER_VARIABLE }}
    steps:
      - name: Ver variable
        run: |
          echo "VALOR DE LA VARIABLE: ${{ vars.MI_PRIMER_VARIABLE }}"
          echo "VALOR DE LA VARIABLE_LOCAL: ${{ env.VARIABLE_LOCAL }}"
          echo "VALOR DE LA VARIABLE_ENTORNO: ${{ env.VARIABLE_ENTORNO }}"
          echo "VALOR DE LA SECRET: ${{ secrets.MI_PRIMER_SECRET }}"
      - name: Run Script
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 el valor de la variable de entorno es ${process.env.MI_PRIMER_VARIABLE}`
            })
